name: Update LGTBot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write

jobs:
  update-lgtbot:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Git setup
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update lgtbot submodule
        run: |
          branch=$(git config -f .gitmodules submodule.lgtbot.branch)
          echo "Updating lgtbot on branch $branch"
          cd lgtbot
          git fetch origin $branch;
          git checkout $branch;
          git pull origin $branch;

      - name: Detect changes
        run: |
          git add lgtbot
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
            git diff --staged --stat
          fi

      - name: Commit & push
        if: env.changes == 'true'
        run: |
          new_hash=$(git -C lgtbot rev-parse --short HEAD)
          git commit -m "update lgtbot submodule to ${new_hash}"
          git push origin HEAD:main
